---
# Custom View - user

resource_name: "SERVICE-TEMPLATE"


actions:
  create_dialog: false
  instantiate_dialog: true
  update_dialog: false
  deploy_dialog: true
  clone: false
  delete: false
  recover: true
  edit_labels: false


filters:
  state: true
  group: true


info-tabs:

  info:
    enabled: true
    information_panel:
      enabled: true
      actions:
        rename: false
    permissions_panel:
      enabled: false
      actions:
        chmod: false
    ownership_panel:
      enabled: false
      actions:
        chown: false
        chgrp: false

  roles:
    enabled: true

  networks:
    enabled: true

  template:
    enabled: true


dialogs:
   deploy_dialog:
   create_dialog:
